<?php

function gsb_feature_fpp_stub_entity_info_alter(&$entity_info) {

  $entity_info['fieldable_panels_pane']['bundles']['test_fpp'] = array(
    'label' => t('Test fpp bundle'),
    'pane category' => t('Test fpp category'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/test-fpp',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

}
